# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Collect_Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Collect_Window(object):
    def setupUi(self, Collect_Window):
        Collect_Window.setObjectName("Collect_Window")
        Collect_Window.resize(545, 392)
        self.centralwidget = QtWidgets.QWidget(Collect_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(264, 90, 20, 171))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(48, 10, 441, 71))
        self.label.setStyleSheet("font: 87 28pt \"Arial Black\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(290, 139, 71, 29))
        self.label_11.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.store = QtWidgets.QPushButton(self.centralwidget)
        self.store.setGeometry(QtCore.QRect(278, 282, 231, 28))
        self.store.setObjectName("store")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(29, 79, 491, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.powerEdit = QtWidgets.QLineEdit(self.frame)
        self.powerEdit.setGeometry(QtCore.QRect(346, 12, 133, 37))
        self.powerEdit.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.powerEdit.setObjectName("powerEdit")
        self.angleEdit = QtWidgets.QLineEdit(self.frame)
        self.angleEdit.setGeometry(QtCore.QRect(346, 55, 133, 37))
        self.angleEdit.setStyleSheet("font: 12pt \"Adobe Heiti Std\";")
        self.angleEdit.setObjectName("angleEdit")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 221, 171))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.point_label_1 = QtWidgets.QLabel(self.widget)
        self.point_label_1.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.point_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.point_label_1.setObjectName("point_label_1")
        self.verticalLayout.addWidget(self.point_label_1)
        self.point_label_2 = QtWidgets.QLabel(self.widget)
        self.point_label_2.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.point_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.point_label_2.setObjectName("point_label_2")
        self.verticalLayout.addWidget(self.point_label_2)
        self.point_label_3 = QtWidgets.QLabel(self.widget)
        self.point_label_3.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.point_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.point_label_3.setObjectName("point_label_3")
        self.verticalLayout.addWidget(self.point_label_3)
        self.wind_power_label = QtWidgets.QLabel(self.widget)
        self.wind_power_label.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.wind_power_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wind_power_label.setObjectName("wind_power_label")
        self.verticalLayout.addWidget(self.wind_power_label)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.point_1 = QtWidgets.QLabel(self.widget)
        self.point_1.setMinimumSize(QtCore.QSize(0, 29))
        self.point_1.setMaximumSize(QtCore.QSize(16777215, 100))
        self.point_1.setStyleSheet("font: 10pt \"Adobe Heiti Std\";")
        self.point_1.setAlignment(QtCore.Qt.AlignCenter)
        self.point_1.setObjectName("point_1")
        self.gridLayout.addWidget(self.point_1, 0, 0, 1, 1)
        self.point_2 = QtWidgets.QLabel(self.widget)
        self.point_2.setMinimumSize(QtCore.QSize(0, 29))
        self.point_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.point_2.setStyleSheet("font: 10pt \"Adobe Heiti Std\";")
        self.point_2.setAlignment(QtCore.Qt.AlignCenter)
        self.point_2.setObjectName("point_2")
        self.gridLayout.addWidget(self.point_2, 1, 0, 1, 1)
        self.point_3 = QtWidgets.QLabel(self.widget)
        self.point_3.setMinimumSize(QtCore.QSize(0, 29))
        self.point_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.point_3.setStyleSheet("font: 14pt \"Adobe Heiti Std\";\n"
"font: 10pt \"Adobe Heiti Std\";")
        self.point_3.setAlignment(QtCore.Qt.AlignCenter)
        self.point_3.setObjectName("point_3")
        self.gridLayout.addWidget(self.point_3, 2, 0, 1, 1)
        self.windPower = QtWidgets.QLineEdit(self.widget)
        self.windPower.setEnabled(True)
        self.windPower.setMinimumSize(QtCore.QSize(0, 29))
        self.windPower.setMaximumSize(QtCore.QSize(16777215, 100))
        self.windPower.setAlignment(QtCore.Qt.AlignCenter)
        self.windPower.setObjectName("windPower")
        self.gridLayout.addWidget(self.windPower, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.hint = QtWidgets.QLabel(self.centralwidget)
        self.hint.setGeometry(QtCore.QRect(289, 180, 219, 80))
        self.hint.setMinimumSize(QtCore.QSize(211, 80))
        self.hint.setStyleSheet("font: 14pt \"Adobe Heiti Std\";\n"
"font: 9pt \"Adobe Heiti Std\";")
        self.hint.setFrameShape(QtWidgets.QFrame.Panel)
        self.hint.setAlignment(QtCore.Qt.AlignCenter)
        self.hint.setObjectName("hint")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(288, 97, 77, 29))
        self.label_10.setStyleSheet("font: 14pt \"Adobe Heiti Std\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.collect = QtWidgets.QPushButton(self.centralwidget)
        self.collect.setGeometry(QtCore.QRect(40, 282, 231, 28))
        self.collect.setObjectName("collect")
        self.frame.raise_()
        self.line.raise_()
        self.label.raise_()
        self.label_11.raise_()
        self.store.raise_()
        self.hint.raise_()
        self.label_10.raise_()
        self.collect.raise_()
        Collect_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Collect_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 545, 26))
        self.menubar.setObjectName("menubar")
        self.menumodel = QtWidgets.QMenu(self.menubar)
        self.menumodel.setObjectName("menumodel")
        Collect_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Collect_Window)
        self.statusbar.setObjectName("statusbar")
        Collect_Window.setStatusBar(self.statusbar)
        self.actionCalculating = QtWidgets.QAction(Collect_Window)
        self.actionCalculating.setObjectName("actionCalculating")
        self.actionCollecting = QtWidgets.QAction(Collect_Window)
        self.actionCollecting.setObjectName("actionCollecting")
        self.menumodel.addAction(self.actionCalculating)
        self.menumodel.addAction(self.actionCollecting)
        self.menubar.addAction(self.menumodel.menuAction())

        self.retranslateUi(Collect_Window)
        QtCore.QMetaObject.connectSlotsByName(Collect_Window)

    def retranslateUi(self, Collect_Window):
        _translate = QtCore.QCoreApplication.translate
        Collect_Window.setWindowTitle(_translate("Collect_Window", "Collecting"))
        self.label.setText(_translate("Collect_Window", "Tank Assistant"))
        self.label_11.setText(_translate("Collect_Window", "ANGLE"))
        self.store.setText(_translate("Collect_Window", "Store"))
        self.point_label_1.setText(_translate("Collect_Window", "Point_1"))
        self.point_label_2.setText(_translate("Collect_Window", "Point_2"))
        self.point_label_3.setText(_translate("Collect_Window", "Point_3"))
        self.wind_power_label.setText(_translate("Collect_Window", "WindPower"))
        self.point_1.setText(_translate("Collect_Window", "X:      Y:"))
        self.point_2.setText(_translate("Collect_Window", "X:      Y:"))
        self.point_3.setText(_translate("Collect_Window", "X:      Y:"))
        self.hint.setText(_translate("Collect_Window", "[HINT]"))
        self.label_10.setText(_translate("Collect_Window", "POWER"))
        self.collect.setText(_translate("Collect_Window", "Collect"))
        self.menumodel.setTitle(_translate("Collect_Window", "model"))
        self.actionCalculating.setText(_translate("Collect_Window", "Calculating"))
        self.actionCollecting.setText(_translate("Collect_Window", "Collecting"))

